HW#10 Оптимизация программы
wursta/otus_go pull request #11
Opened 2024-05-04 19:13 UTC by wursta

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-05-04 19:45 UTC, wursta commented
Результаты Benchstat:

|  | benchmark_old.txt | benchmark_new.txt | **vs base** |
|--------|--------|--------|--------|
|  | **sec/op** | **sec/op** |  |
| GetDomainStat-8 | 5.474m ± 18% | 6.853m ± 13% | +25.20% (p=0.009 n=10) |
|  | **B/op** | **b/op** |  |
| GetDomainStat-8 | 1536.39Ki ± 26% | 74.89Ki ± 18% | -95.13% (p=0.000 n=10) |
|  | **allocs/op** | **allocs/op** |  |
| GetDomainStat-8 | 15.277k ± 26% | 3.884k ± 19% |  -74.58% (p=0.000 n=10) |

2024-05-04 20:34 UTC, vladislavmass requested changes

2024-05-04 20:34 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  		result[i] = user
А что будет если у меня вдруг в документе окажется не 100 000 пользователей, а 200 000 или 100 001

2024-05-04 20:34 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  type User struct {
Нам точно нужны все поля этой структуры?

2024-05-04 20:34 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +		matched := regex.MatchString(user.Email)
Как поведет себя этот код например если у меня email vasya.com@mail.net и я  захочу получу стату по домену com

2024-05-04 20:34 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  			num := result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]
Тут будет паника если в строке не будет символа собаки

2024-05-04 20:34 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  func countDomains(u users, domain string) (DomainStat, error) {
А нам точно нужно 2 метода и гонять между ними данные? Или можно как то иначе?

2024-05-05 07:47 UTC, wursta commented on hw10_program_optimization/stats.go
>  		result[i] = user
Переделал, данного кода больше нет

2024-05-05 07:47 UTC, wursta commented on hw10_program_optimization/stats.go
>  type User struct {
Согласен, оставил только Email

2024-05-05 07:47 UTC, wursta commented on hw10_program_optimization/stats.go
> +		matched := regex.MatchString(user.Email)
Исправил регулярное выражение, теперь такого быть не может.

2024-05-05 07:49 UTC, wursta commented on hw10_program_optimization/stats.go
>  			num := result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]
Новая регулярка теперь исключает такое. Добавил в тест пример на такой случай.

2024-05-05 07:50 UTC, wursta commented on hw10_program_optimization/stats.go
>  func countDomains(u users, domain string) (DomainStat, error) {
Согласен. Переделал все в 1 метод.

2024-05-05 07:54 UTC, wursta commented
Новые результаты Benchstat:

|  | benchmark_old.txt | benchmark_new.txt | **vs base** |
|--------|--------|--------|--------|
|  | **sec/op** | **sec/op** |  |
| GetDomainStat-8 | 5.474m ± 18% | 4.058µ ± 6% | -99.93% (p=0.000 n=10) |
|  | **B/op** | **B/op** |  |
| GetDomainStat-8 | 1536.39Ki ± 26% | 6.417Ki ± 0% | -99.58% (p=0.000 n=10) |
|  | **allocs/op** | **allocs/op** |  |
| GetDomainStat-8 | 15.277k ± 26% | 26.00 ± 0% |  -99.83% (p=0.000 n=10) |

2024-05-05 11:13 UTC, vladislavmass approved these changes

2024-05-05 11:13 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +		matched := regex.MatchString(user.Email)
HasSuffix и проверка размера слайса после Split работали бы быстрее

2024-05-05 16:07 UTC, merged