HW#4
wursta/otus_go pull request #5
Opened 2024-03-04 17:02 UTC by wursta

Реализация интерфейса List

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-06 07:13 UTC, vladislavmass requested changes

2024-03-06 07:13 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	queue  *ListItem
Для полей выбраны очень странные имена

2024-03-06 07:13 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (l *list) Remove(i *ListItem) {
Не вижу в этом коде зануление queue при удаление единственного элемента

2024-03-06 14:42 UTC, wursta commented on hw04_lru_cache/list.go
> +	queue  *ListItem
Согласен. Поменял на более понятные

2024-03-06 14:43 UTC, wursta commented on hw04_lru_cache/list.go
> +func (l *list) Remove(i *ListItem) {
Точно. Спасибо.
Доработал тест, чтобы это проверялось.

2024-03-06 18:47 UTC, vladislavmass requested changes

2024-03-06 18:47 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (l *list) Remove(i *ListItem) {
А если мы удаляем первый элемент нам не надо обновить `l.firstItem `

2024-03-07 11:47 UTC, wursta commented on hw04_lru_cache/list.go
> +func (l *list) Remove(i *ListItem) {
Да. Надо. Исправил, доработал тест.

2024-03-07 21:04 UTC, vladislavmass approved these changes

2024-03-07 21:04 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i.Next != nil {
Зачем делать еще одно сравнение, если мы уже делали проверку противоположного условия?

2024-03-07 21:04 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i.Prev == nil {
В строках 70 и 79, 74 и 82 взаимоисключающие условия

2024-03-09 17:13 UTC, merged